'use client';

interface FAQProps {
  locale?: string;
}

const FAQ_ITEMS = [
  {
    question: 'How to use Sora prompt generator to create AI videos?',
    answer: `Just three simple steps:
1) Enter your video creative idea
2) Select your desired video type
3) Click the "Generate AI Prompt" button

Our AI Sora prompt generator will immediately generate optimized professional-level Sora 2 prompts for you.`,
  },
  {
    question: 'Can the generated Sora prompt be used directly in Sora 2?',
    answer: 'Yes! All Sora prompts generated by our Sora prompt generator are fully compatible with Sora 2 AI video generator. You can directly copy the generated Sora prompts to Sora 2 official platform and immediately generate the high-quality videos you want.',
  },
  {
    question: 'Is there a limit to the number of prompts I can generate?',
    answer: 'No limits! You can generate unlimited Sora prompts and create unlimited AI video prompts. All historical prompt records are saved in your account for easy viewing and reuse of our Sora prompts.',
  },
  {
    question: 'Is the free Sora prompt generator really completely free?',
    answer: 'Yes! Sora-Prompt 100% free to use. We promise no fees, no credit card required, no hidden costs. Free use of our Sora AI prompt generation tool to create unlimited high-quality Sora prompts.',
  },
  {
    question: 'How to contact Sora prompt generator technical support?',
    answer: 'You can contact our support team in multiple ways. Send an email to support@sora-prompt.io, or click the "Contact" link at the bottom of the page. Our professional team will reply to your questions within 24 hours.',
  },
  {
    question: 'What is Sora-Prompt? Why choose our Sora prompt generator?',
    answer: `Welcome to sora-prompt, the most powerful Sora prompt generator. Our Sora AI prompt generator can help you quickly generate high-quality Sora prompts. Whether you want to create Sora video prompts or Sora image prompts, you can use our tool to generate professional-level prompts with one click.

This is a free Sora Prompt Generator, specially designed for Sora 2 prompt generator users. Whether you need a Sora AI prompt generator or Sora 2 Prompt Generator, we can help you quickly generate optimized Sora prompts, helping you create more viral-friendly viral Sora 2 prompt content.

Our AI video generation Sora tool is completely free to use and supports generating various types of video prompts, including all the functionality required by the free Sora AI video generator. Start using Sora prompts now and create your next AI video masterpiece!`,
  },
];

export default function FAQ({ locale = 'en' }: FAQProps) {
  return (
    <div className="py-10 px-4 bg-yellow-50 border-t border-gray-200">
      <div className="max-w-5xl mx-auto">
        {/* Section Title */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-800">
            ❓ 常见问题 - Sora 提示词生成器 FAQ
          </h2>
        </div>

        {/* FAQ Items */}
        <div className="space-y-6">
          {FAQ_ITEMS.map((item, index) => (
            <div key={index} className="pb-6 border-b border-gray-300 last:border-b-0">
              <h3 className="text-base font-semibold text-gray-800 mb-3 cursor-pointer hover:text-green-600 transition-colors">
                {item.question}
              </h3>
              <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">
                {item.answer}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
